### ISSUE TITLE
Repeat the process

### ISSUE THREAD

**Issue by Mo-0hammed** [zhgzhg/GPhpThread#1]
When I create a process that works normally but at work iterates on its own why

**Comment by zhgzhg** [comment]
Could you give a concrete code example?

**Comment by Mo-0hammed** [comment]
> Could you give a concrete code example?

<?php 
require_once 'GPhpThread.php';
class Bot extends GPhpThread
{
    private function sendCommand($command, $data = false, $Token = null)
    {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, "https://api.telegram.org/bot" . $Token . "/$command");
        curl_setopt($ch, CURLOPT_POST, count($data));
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $result = curl_exec($ch);
        curl_close($ch);
        return $result;
    }

    public function run()
    {
        for ($i=0; $i < 3000; $i++) { 
            $this->sendCommand('sendMessage', ['chat_id' => 1, 'text' => 'test'], '11');
        }
    }
}
$nothing = null;
$Bot = new Bot($nothing, true);
$Bot->start();

**Comment by Mo-0hammed** [comment]
```
<?php 
require_once 'GPhpThread.php';
class Bot extends GPhpThread{
    private function sendCommand($command, $data = false, $Token = null){
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, "https://api.telegram.org/bot" . $Token . "/$command");
        curl_setopt($ch, CURLOPT_POST, count($data));
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $result = curl_exec($ch);
        curl_close($ch);
        return $result;
    }

    public function run(){
        for ($i=0; $i < 3000; $i++) { 
            $this->sendCommand('sendMessage', ['chat_id' => 1, 'text' => 'test'], '11');
        }
    }
}
$nothing = null;
$Bot = new Bot($nothing, true);
$Bot->start();
```

**Comment by zhgzhg** [comment]
I can see that you are setting the $allowThreadExitCodes parameter to 'true':

`$Bot = new Bot($nothing, true);`

Depending on how your applications is structured this may be cause, so I'd suggest trying with 'false'. If you need thread exit codes (which your example doesn't suggest) you'll have to make sure that before the creation of a heavy thread there are no initialized objects whose destructors and particularly their multiple execution (in all the children and once in the parent) will affect the execution of the program in an undefined way.

You can check the documentation here:
[https://htmlpreview.github.io/?https://raw.githubusercontent.com/zhgzhg/GPhpThread/master/Documentation/classes/GPhpThread.html#method___construct](https://htmlpreview.github.io/?https://raw.githubusercontent.com/zhgzhg/GPhpThread/master/Documentation/classes/GPhpThread.html#method___construct)

An example dealing with this situation is:
[https://github.com/zhgzhg/GPhpThread/blob/master/examples/ThreadFromThread.php](https://github.com/zhgzhg/GPhpThread/blob/master/examples/ThreadFromThread.php)
